# Define Variables
@token =
@host = http://localhost:8000

### GET request to retrieve all entity pages
GET {{host}}/api/pages
Accept: application/json
Authorization: Bearer {{token}}

### POST request to create a new entity page
POST {{host}}/api/pages
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "title": "New Page 2",
    "route": "new-page-2",
    "page_items": [
        {
            "type": "textItem",
            "title": "Heading",
            "body": "<h1>Welcome to our new page!</h1>"
        },
        {
            "type": "imageItem",
            "file_id": null
        },
        {
            "type": "textItem",
            "title": "Description",
            "body": "<p>This is a description of our new page.</p>"
        }
    ]
}

### GET request to retrieve a specific entity page by ID
GET {{host}}/api/pages/1
Accept: application/json
Authorization: Bearer {{token}}

### PUT request to update a specific entity page by ID
PUT {{host}}/api/pages/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "id": 1,
  "title": "Testpage",
  "route": null,
  "created_at": "2023-04-11T19:12:52.000000Z",
  "updated_at": "2023-04-11T19:12:52.000000Z",
  "page_items": [
    {
      "id": 1,
      "type": "text",
      "sort": 10,
      "created_at": "2023-04-11T19:13:36.000000Z",
      "updated_at": "2023-04-11T19:13:36.000000Z",
      "text_item_id": 1,
      "page_item_id": 1,
      "title": "kmkmklm",
      "body": "<h5>iomk asdfasdf adsfasdfasdfa asdf mklml mmkmlmkl<\/h5>"
    },
    {
      "id": 2,
      "type": "text",
      "sort": 55,
      "created_at": "2023-04-11T19:14:01.000000Z",
      "updated_at": "2023-04-11T19:14:01.000000Z",
      "text_item_id": 2,
      "page_item_id": 2,
      "title": "kmkmklm",
      "body": "<h5>iomk asdfasdf adsfasdfasdfa asdf mklml mmkmlmkl<\/h5>"
    }
  ]
}

### DELETE request to delete a specific entity page by ID
DELETE {{host}}/api/pages/1
Accept: application/json
Authorization: Bearer {{token}}