-- migrate:up
DELETE FROM `successor_groups` WHERE `id` = '8';
DELETE FROM `successor_groups` WHERE `id` = '7';
DELETE FROM `successor_groups` WHERE `id` = '6';
DELETE FROM `successor_groups` WHERE `id` = '5';
DELETE FROM `successor_groups` WHERE `id` = '4';
DELETE FROM `successor_groups` WHERE `id` = '3';
DELETE FROM `successor_groups` WHERE `id` = '2';
DELETE FROM `successor_groups` WHERE `id` = '1';
ALTER TABLE `page_contents` ADD `form_title` varchar(200) DEFAULT NULL;
ALTER TABLE `contacts` ADD `position` varchar(200) DEFAULT NULL;
ALTER TABLE `page_contents` ADD `form_email` varchar(200) DEFAULT NULL COMMENT 'Die Antwort des Formulars wird an die angegebene E-Mail Adresse gesendet.';
INSERT INTO `events` VALUES('2','Aktivität 2','<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>','2021-01-01 14:00:00','2','2021-01-01 17:00:00','2','<p>Zvieri</p>
<p>Ztrinke</p>
<p>Pfadihemd</p>','published','1','2020-06-23 15:50:34','1','2020-06-23 15:52:02');
INSERT INTO `successor_groups` VALUES('10','1','3');
INSERT INTO `page_contents` VALUES('10','5',NULL,NULL,NULL,'1','2020-06-23 15:28:17',NULL,NULL,'[{\"newItem\":true,\"title\":\"Anl\\u00e4sse\",\"type\":\"events\"},{\"newItem\":true,\"title\":\"Jahresplan\",\"type\":\"anual_plan\"},{\"newItem\":true,\"title\":\"Special Events\",\"type\":\"special_events\"}]',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `directus_files` VALUES('25','local','9cmpek8jjwo4g84k','4c19ef79-36e7-4de8-94bc-e7c741cec070.svg','Bibergruppe_1.svg','Bibergruppe 1','image/svg+xml','1','2020-06-23 15:11:26','','5291',NULL,NULL,'0',NULL,NULL,'','','','693764848dcbe354ebc319eb801d1192',NULL);
INSERT INTO `pages` VALUES('2','Mitmachen','published','22',NULL,'2020-06-23 13:52:46','1','2020-06-23 14:08:44','mitmachen');
INSERT INTO `pages` VALUES('3','Wer wir sind','published','22',NULL,'2020-06-23 14:30:40','1','2020-06-23 14:30:40','wer-wir-sind');
INSERT INTO `pages` VALUES('4','Was wir tun','published','22',NULL,'2020-06-23 14:32:40','1','2020-06-23 14:32:40','was-wir-tun');
INSERT INTO `pages` VALUES('5','Agenda','published','22',NULL,'2020-06-23 15:28:17','1','2020-06-23 15:28:17','agenda');
INSERT INTO `special_events` VALUES('1','Waldweihnacht','Waldweihnachten','<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>','published',NULL,'2020-06-23 15:56:16','1','2020-06-23 15:56:38');
INSERT INTO `special_events` VALUES('2','Gloggitag','Gloggitag','<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>','published',NULL,'2020-06-23 15:56:32','1','2020-06-23 15:56:32');
INSERT INTO `successor_groups` VALUES('9','1','2');
INSERT INTO `successor_groups` VALUES('11','2','4');
INSERT INTO `page_contents` VALUES('8','3',NULL,NULL,NULL,'1','2020-06-23 14:30:40',NULL,NULL,NULL,'1',NULL,'1',NULL,NULL,NULL,NULL);
INSERT INTO `successor_groups` VALUES('12','3','5');
INSERT INTO `successor_groups` VALUES('13','4','6');
INSERT INTO `successor_groups` VALUES('14','5','6');
INSERT INTO `directus_files` VALUES('24','local','sdeeczhgjas8ss4w','0e7b72be-0265-404f-9524-9104efc2f94b.png','dummy-profile-300x284.png','Dummy Profile 300x284','image/png','1','2020-06-23 14:27:29','binary','18987','300','284','0',NULL,NULL,'','','','2de1776a5f680b5e150f2a18d7759493',NULL);
INSERT INTO `directus_fields` VALUES('331','contacts','position','string','text-input','{\"trim\":true,\"showCharacterCount\":true,\"formatValue\":false,\"monospace\":false}','0',NULL,'0','0','0','0','3','full',NULL,NULL,'[]');
INSERT INTO `directus_fields` VALUES('330','page_contents','form_email','string','text-input','{\"trim\":true,\"showCharacterCount\":false,\"formatValue\":false,\"monospace\":false}','0','/[-a-zA-Z0-9_.+]+@[-.a-z]+\\.[-a-z]+/','0','0','0','0','8','full',NULL,'Die Antwort des Formulars wird an die angegebene E-Mail Adresse gesendet.','[{\"newItem\":true,\"locale\":\"de-DE\",\"translation\":\"Formular E-Mail\"}]');
INSERT INTO `directus_fields` VALUES('329','page_contents','form_title','string','text-input','{\"trim\":true,\"showCharacterCount\":false,\"formatValue\":false,\"monospace\":false}','0',NULL,'0','0','0','0','7','full',NULL,NULL,'[{\"newItem\":true,\"locale\":\"de-DE\",\"translation\":\"Formulartitel\"}]');
INSERT INTO `contacts` VALUES('2','Maxine Musterfrau v/o Ganula','psl@gloggi.ch','24','published',NULL,'2020-06-23 14:29:26','1','2020-06-23 14:29:26','PSL');
INSERT INTO `contacts` VALUES('1','Max Mustermann v/o Frosch','al@gloggi.ch','24','published',NULL,'2020-06-23 14:28:36','1','2020-06-23 14:28:36','Abteilungsleiter');
INSERT INTO `page_contents` VALUES('9','4',NULL,NULL,NULL,'1','2020-06-23 14:32:40',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL);
INSERT INTO `page_contents` VALUES('7','2',NULL,'<p>Mach mit! Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>',NULL,'1','2020-06-23 14:08:44','[{\"newItem\":true,\"name\":\"Vorname\",\"type\":\"text\",\"required\":true},{\"newItem\":true,\"name\":\"Nachname\",\"type\":\"text\",\"required\":true},{\"newItem\":true,\"name\":\"Geburtstag\",\"type\":\"date\",\"required\":true},{\"newItem\":true,\"name\":\"E-Mail\",\"type\":\"email\",\"required\":true}]',NULL,NULL,NULL,NULL,'1',NULL,NULL,'Mitmachen','test@test.com');
INSERT INTO `events` VALUES('3','Aktivität 3','<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>','2021-01-01 14:00:00','4','2021-01-01 17:00:00','4','<p>Pfadihemd</p>
<p>Kravatte</p>','published','1','2020-06-23 15:51:40','1','2020-06-23 15:51:40');
INSERT INTO `events_groups` VALUES('6','6','5');
INSERT INTO `events` VALUES('4','Aktivität 4','','2021-07-04 14:00:00','3','2021-07-04 16:00:00','3','<p>Zvieri</p>
<p>Ztrinke</p>','published','1','2020-06-23 15:53:16','1','2020-06-23 15:54:43');
INSERT INTO `events` VALUES('5','Aktivität 5','<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>','2021-07-04 14:00:00','5','2021-07-04 17:00:00','5','<p>Zvieri</p>
<p>Ztrinke</p>','published','1','2020-06-23 15:54:30','1','2020-06-23 15:54:56');
INSERT INTO `events` VALUES('6','Aktivität 6','<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>','2021-07-04 14:00:00','4','2021-07-04 17:00:00','4','<p>Pfadihemd</p>
<p>Kravatte</p>','published','1','2020-06-23 15:55:50','1','2020-06-23 15:55:50');
INSERT INTO `events` VALUES('7','Abteilungsaktivität','<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>','2021-07-11 12:00:00','1','2021-07-11 18:00:00','4','<p>Pfadihemd</p>
<p>Kravatte</p>','published','1','2020-06-23 15:58:04','1','2020-06-23 15:58:04');
INSERT INTO `events_groups` VALUES('1','1','1');
INSERT INTO `events_groups` VALUES('2','2','2');
INSERT INTO `events_groups` VALUES('3','3','4');
INSERT INTO `events_groups` VALUES('4','4','1');
INSERT INTO `events_groups` VALUES('5','5','2');
INSERT INTO `events_groups` VALUES('7','7','1');
INSERT INTO `page_contents` VALUES('6','1','22','<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>',NULL,'1','2020-06-23 13:49:17',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `events_groups` VALUES('8','7','2');
INSERT INTO `events_groups` VALUES('9','7','3');
INSERT INTO `events_groups` VALUES('10','7','4');
INSERT INTO `events_groups` VALUES('11','7','5');
INSERT INTO `events_groups` VALUES('12','7','6');
INSERT INTO `locations` VALUES('1','Bahnhof Schwerzenbach','{\"x\":2692131,\"y\":1248890}','published','2020-06-23 15:41:37','1','2020-06-23 15:41:37');
INSERT INTO `events` VALUES('1','Aktivität 1','<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>','2021-01-01 14:00:00','1','2021-01-01 16:00:00','1','<p>Zvieri</p>
<p>Ztrinke</p>','published','1','2020-06-23 15:47:20','1','2020-06-23 15:47:20');
INSERT INTO `locations` VALUES('3','Friedhof Schwerzenbach','{\"x\":2692134,\"y\":1248384}','published','2020-06-23 15:42:42','1','2020-06-23 15:42:42');
INSERT INTO `locations` VALUES('4','Friedhof Volketswil','{\"x\":2694227,\"y\":1248993}','published','2020-06-23 15:43:53','1','2020-06-23 15:43:53');
INSERT INTO `locations` VALUES('5','Schützenhaus Hegnau','{\"x\":2693241,\"y\":1250155}','published','2020-06-23 15:44:41','1','2020-06-23 15:44:41');
INSERT INTO `locations` VALUES('2','Bruggeln','{\"x\":2694910,\"y\":1250343}','published','2020-06-23 15:42:15','1','2020-06-23 15:42:15');


-- migrate:down
DELETE FROM `locations` WHERE `id` = '1';
DELETE FROM `page_contents` WHERE `id` = '8';
DELETE FROM `events_groups` WHERE `id` = '11';
DELETE FROM `events_groups` WHERE `id` = '12';
DELETE FROM `successor_groups` WHERE `id` = '13';
DELETE FROM `locations` WHERE `id` = '2';
DELETE FROM `locations` WHERE `id` = '3';
DELETE FROM `locations` WHERE `id` = '4';
DELETE FROM `locations` WHERE `id` = '5';
DELETE FROM `page_contents` WHERE `id` = '6';
DELETE FROM `page_contents` WHERE `id` = '7';
DELETE FROM `page_contents` WHERE `id` = '9';
DELETE FROM `events_groups` WHERE `id` = '9';
DELETE FROM `page_contents` WHERE `id` = '10';
DELETE FROM `pages` WHERE `id` = '2';
DELETE FROM `pages` WHERE `id` = '3';
DELETE FROM `pages` WHERE `id` = '4';
DELETE FROM `pages` WHERE `id` = '5';
DELETE FROM `special_events` WHERE `id` = '1';
DELETE FROM `special_events` WHERE `id` = '2';
DELETE FROM `successor_groups` WHERE `id` = '9';
DELETE FROM `successor_groups` WHERE `id` = '10';
DELETE FROM `events_groups` WHERE `id` = '10';
DELETE FROM `events_groups` WHERE `id` = '8';
DELETE FROM `successor_groups` WHERE `id` = '12';
DELETE FROM `events` WHERE `id` = '2';
DELETE FROM `successor_groups` WHERE `id` = '14';
DELETE FROM `contacts` WHERE `id` = '1';
DELETE FROM `contacts` WHERE `id` = '2';
DELETE FROM `directus_fields` WHERE `id` = '329';
DELETE FROM `directus_fields` WHERE `id` = '330';
DELETE FROM `directus_fields` WHERE `id` = '331';
DELETE FROM `directus_files` WHERE `id` = '24';
DELETE FROM `directus_files` WHERE `id` = '25';
DELETE FROM `events` WHERE `id` = '1';
DELETE FROM `events` WHERE `id` = '3';
DELETE FROM `events_groups` WHERE `id` = '7';
DELETE FROM `events` WHERE `id` = '4';
DELETE FROM `events` WHERE `id` = '5';
DELETE FROM `events` WHERE `id` = '6';
DELETE FROM `events` WHERE `id` = '7';
DELETE FROM `events_groups` WHERE `id` = '1';
DELETE FROM `events_groups` WHERE `id` = '2';
DELETE FROM `events_groups` WHERE `id` = '3';
DELETE FROM `events_groups` WHERE `id` = '4';
DELETE FROM `events_groups` WHERE `id` = '5';
DELETE FROM `events_groups` WHERE `id` = '6';
DELETE FROM `successor_groups` WHERE `id` = '11';
ALTER TABLE `contacts` DROP `position`;
ALTER TABLE `page_contents` DROP `form_title`;
ALTER TABLE `page_contents` DROP `form_email`;
INSERT INTO `successor_groups` VALUES('1','2','1');
INSERT INTO `successor_groups` VALUES('2','3','1');
INSERT INTO `successor_groups` VALUES('3','4','2');
INSERT INTO `successor_groups` VALUES('4','4','3');
INSERT INTO `successor_groups` VALUES('5','5','2');
INSERT INTO `successor_groups` VALUES('6','5','3');
INSERT INTO `successor_groups` VALUES('7','6','4');
INSERT INTO `successor_groups` VALUES('8','6','5');
