-- migrate:up

INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'age_levels',2,'published','none','full','none','none','none','none',NULL,NULL,NULL);
INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'contacts',2,'published','none','full','none','none','none','none',NULL,NULL,NULL);
INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'event_attachments',2,'published','none','full','none','none','none','none',NULL,NULL,NULL);
INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'events',2,'published','none','full','none','none','none','none',NULL,NULL,NULL);
INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'events_groups',2,NULL,'none','full','none','none','none','none',NULL,NULL,NULL);
INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'events_special_events',2,NULL,'none','full','none','none','none','none',NULL,NULL,NULL);
INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'group_images',2,NULL,'none','full','none','none','none','none',NULL,NULL,NULL);
INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'groups',2,'published','none','full','none','none','none','none',NULL,NULL,NULL);
INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'locations',2,'published','none','full','none','none','none','none',NULL,NULL,NULL);
INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'page_contents',2,NULL,'none','full','none','none','none','none',NULL,NULL,NULL);
INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'pages',2,'published','none','full','none','none','none','none',NULL,NULL,NULL);
INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'settings',2,NULL,'none','full','none','none','none','none',NULL,NULL,NULL);
INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'special_events',2,'published','none','full','none','none','none','none',NULL,NULL,NULL);
INSERT INTO `directus_permissions` (`id`, `collection`, `role`, `status`, `create`, `read`, `update`, `delete`, `comment`, `explain`, `read_field_blacklist`, `write_field_blacklist`, `status_blacklist`) VALUES(null,'successor_groups',2,NULL,'none','full','none','none','none','none',NULL,NULL,NULL);
