version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Frontend (Vue/NPM)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  # API (Laravel/Composer)
  - package-ecosystem: "composer"
    directory: "/api"
    schedule:
      interval: "weekly"

  # API (Vite/NPM)
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"

  # Docker compose
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker (API)
  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"

  # Docker (Frontend)
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
