### Login
POST http://localhost/login
Accept: application/json
Content-Type: application/json

{ 
    "username": "foo",
    "password": "foo"
    }

### Delete
DELETE http://localhost/media_objects/1
Accept: application/json
Content-Type: application/json