#!/bin/sh
set -e

# Drop the duplicate DB if it exists
dbmate -e "DIFF_DATABASE_URL" --wait drop

# Recreate the DB state from the existing migrations in a separate DB
dbmate -e "DIFF_DATABASE_URL" --wait --no-dump-schema up

# Create a migration that represents the difference between the two databases
MIGRATION_NAME="$(date +"%Y%m%d%H%M%S")_edit-me.sql"
dbdiff --config=/db/dbdiff-config.yml server1.directus:server1.directus_diff --output=/db/migrations/"$MIGRATION_NAME"

# Drop the separate DB
dbmate -e "DIFF_DATABASE_URL" --wait drop

# Update the schema.sql
dbmate --wait dump
